/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CitySlugRouteImport } from './routes/city.$slug'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emergency': typeof EmergencyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/trust': typeof TrustRoute
  '/city/$slug': typeof CitySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emergency': typeof EmergencyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/trust': typeof TrustRoute
  '/city/$slug': typeof CitySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emergency': typeof EmergencyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/trust': typeof TrustRoute
  '/city/$slug': typeof CitySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/emergency'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/trust'
    | '/city/$slug'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emergency'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/trust'
    | '/city/$slug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/emergency'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/trust'
    | '/city/$slug'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmergencyRoute: typeof EmergencyRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TrustRoute: typeof TrustRoute
  CitySlugRoute: typeof CitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmergencyRoute: EmergencyRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TrustRoute: TrustRoute,
  CitySlugRoute: CitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
